-- Seed initial tavern data for The Dude Network

INSERT INTO public.taverns (slug, name, city, county, state, region, address, short_description, long_description, thumbnail, tags, video_title, video_url, video_platform, latitude, longitude, featured, dude_approved, rating, stop_number)
VALUES
(
  'kellys-corner-bar',
  'Kelly''s Corner Bar',
  'Chillicothe',
  'Ross',
  'OH',
  'South Ohio',
  '247 N Paint St, Chillicothe, OH 45601',
  'A no-frills corner bar that''s been pouring cold ones since 1958. Dark, loud, and perfect.',
  'Kelly''s Corner Bar is exactly what Ohio tavern culture is about. Vinyl bar stools that have seen decades of regulars, a jukebox that only plays country and classic rock, and Bud on draft for $2.50. The wings are legendary — dry rub, crispy, served in a basket with a side of blue cheese. Don''t let the unmarked door fool you: this place is a living piece of Ross County history. The regulars will treat you like family by your second beer.',
  '/images/tavern-1.jpg',
  ARRAY['Hidden Gem', 'Cold Beer', 'Great Wings', 'Historic Spot'],
  'Stop #4 — Kelly''s Corner Bar, Chillicothe OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  39.332,
  -82.982,
  true,
  true,
  4.8,
  4
),
(
  'the-rusty-rail',
  'The Rusty Rail',
  'Zanesville',
  'Muskingum',
  'OH',
  'Southeast Ohio',
  '412 Main St, Zanesville, OH 43701',
  'Former railroad workers'' bar with 100 years of grit baked into the walls. Order the rail special.',
  'The Rusty Rail sits one block from the old Muskingum River rail yards, and you can feel it. The building dates to 1921, and the current owner''s grandfather opened the bar here in 1947. The tap selection rotates local Ohio craft alongside the classics. There''s a back room with darts and shuffleboard, and on Friday nights a local band squeezes onto a tiny corner stage. This is a destination stop.',
  '/images/tavern-2.jpg',
  ARRAY['Historic Spot', 'Live Music', 'Road Trip Worthy', 'Local Legend'],
  'Stop #7 — The Rusty Rail, Zanesville OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  39.9403,
  -82.0132,
  true,
  true,
  4.6,
  7
),
(
  'petes-place',
  'Pete''s Place',
  'McConnelsville',
  'Morgan',
  'OH',
  'Southeast Ohio',
  '19 W Main St, McConnelsville, OH 43756',
  'Tiny river town gem. Pete himself still tends bar and knows every customer by name.',
  'Population 1,600. One bar worth talking about. Pete''s Place is a single-room bar on the main drag of McConnelsville, right off the Muskingum River. Pete has been behind the bar for 34 years. The Ohio State memorabilia covers every inch of wall space. The kitchen does Friday fish fry that draws people from three counties. Cash only. ATM in the back. Worth every penny.',
  '/images/tavern-3.jpg',
  ARRAY['Hidden Gem', 'Small Town Stop', 'Local Legend', 'Dive Bar'],
  'Stop #11 — Pete''s Place, McConnelsville OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  39.6467,
  -81.8566,
  true,
  true,
  4.9,
  11
),
(
  'the-taproom-at-brewster',
  'The Taproom at Brewster',
  'Brewster',
  'Stark',
  'OH',
  'Northeast Ohio',
  '102 Wabash Ave S, Brewster, OH 44613',
  'Best patio in Stark County, cold craft drafts, and wings that people drive 45 minutes for.',
  'Don''t let the industrial surroundings fool you. The Taproom at Brewster has built a loyal following on the strength of its 20-tap beer list, half-price wing nights, and a covered patio that fits 80 people. The bartenders are fast and the crowd is real. This is the kind of bar that makes you feel like a regular on your first visit. We gave it our highest Atmosphere rating of the entire tour so far.',
  '/images/tavern-4.jpg',
  ARRAY['Great Wings', 'Cold Beer', 'Best Atmosphere', 'Road Trip Worthy'],
  'Stop #14 — The Taproom at Brewster, OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  40.7067,
  -81.8413,
  true,
  true,
  4.7,
  14
),
(
  'deans-bar-and-grill',
  'Dean''s Bar & Grill',
  'Gallipolis',
  'Gallia',
  'OH',
  'South Ohio',
  '318 2nd Ave, Gallipolis, OH 45631',
  'River town classic. Catfish on the menu, cold Stroh''s on tap, and stories that go back decades.',
  'Gallipolis sits right on the Ohio River, and Dean''s Bar & Grill has been fueling the town since 1963. The catfish sandwich is undefeated. Stroh''s on draft — yes, still. The back wall is covered in photos going back to the ''70s. Dean''s grandson now runs the place and hasn''t changed a thing, which is exactly the right call. This is where south Ohio comes to exhale.',
  '/images/tavern-5.jpg',
  ARRAY['Historic Spot', 'Small Town Stop', 'Local Legend', 'Hidden Gem'],
  'Stop #18 — Dean''s Bar & Grill, Gallipolis OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'tiktok',
  38.8312,
  -82.1977,
  true,
  true,
  4.5,
  18
),
(
  'black-horse-saloon',
  'Black Horse Saloon',
  'Mt. Vernon',
  'Knox',
  'OH',
  'Central Ohio',
  '11 S Main St, Mt Vernon, OH 43050',
  'Old-school Knox County bar with a pool table, a dartboard, and zero pretension.',
  'Mt. Vernon is the kind of Ohio small city that still has a real downtown, and Black Horse Saloon is its anchor bar. Pool table in the back, covered patio out front, and a burger that beats any chain within 40 miles. The crowd skews blue-collar and friendly. The bartender will talk football with you for an hour. We hit this stop on a Tuesday and it was packed — which tells you everything.',
  '/images/tavern-6.jpg',
  ARRAY['Cold Beer', 'Best Atmosphere', 'Dive Bar', 'Road Trip Worthy'],
  'Stop #21 — Black Horse Saloon, Mt. Vernon OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  40.3934,
  -82.4852,
  true,
  true,
  4.6,
  21
),
(
  'farmhouse-tap',
  'Farmhouse Tap',
  'Millersburg',
  'Holmes',
  'OH',
  'Northeast Ohio',
  '65 N Washington St, Millersburg, OH 44654',
  'Amish country''s best-kept secret. Great local drafts and food that''s anything but plain.',
  'You wouldn''t expect a craft tap bar in the heart of Holmes County''s Amish country, but Millersburg is full of surprises. Farmhouse Tap pours Ohio craft brews alongside a rotating selection of regionals. The kitchen turns out elevated bar food — think fried perch, Ohio cheese boards, and house-smoked meats. The vibe is warm and unhurried. This one made our short list for Best New Discovery of the tour.',
  '/images/tavern-7.jpg',
  ARRAY['Hidden Gem', 'Road Trip Worthy', 'Best Atmosphere', 'Local Legend'],
  'Stop #24 — Farmhouse Tap, Millersburg OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'tiktok',
  40.5534,
  -81.9185,
  false,
  false,
  4.8,
  24
),
(
  'the-original-nick-bar',
  'The Original Nick Bar',
  'Portsmouth',
  'Scioto',
  'OH',
  'South Ohio',
  '826 Gallia St, Portsmouth, OH 45662',
  'They''ve been pouring since Prohibition ended and they haven''t stopped. This is the real thing.',
  'The Original Nick Bar in Portsmouth may be the oldest continuously-operating tavern we''ve visited. The bar itself is solid oak, original to the 1933 build. The back bar back bar mirror has a crack in it from 1957 that nobody ever fixed because why would you. The town has had its struggles, but Nick Bar is still here, still serving, still exactly what a tavern is supposed to be. We stayed four hours. No regrets.',
  '/images/tavern-8.jpg',
  ARRAY['Historic Spot', 'Dive Bar', 'Local Legend', 'Cold Beer'],
  'Stop #27 — The Original Nick Bar, Portsmouth OH',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'youtube',
  38.7318,
  -82.9977,
  false,
  false,
  4.9,
  27
)
ON CONFLICT (slug) DO NOTHING;
